99_cats/nine9_cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cats#index"

  resources :cats, except: :destroy
end

99_cats/nine9_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

99_cats/nine9_cats/app/models/cat.rb
require "action_view"

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    CAT_COLORS = %w(white black gray ginger purple)
    validate :birth_date_cannot_be_future
    validates :name, presence: true
    validates :color, inclusion: { in: CAT_COLORS }, presence: true
    validates :sex, inclusion: { in: %w(F M) }

    def age
        # time_ago_in_words(DateTime.now.year - birth_date.year)
        DateTime.now.year - birth_date.year
    end

    private
    def birth_date_cannot_be_future
        if birth_date > DateTime.now
            errors.add(:birth_date, 'can\'t be in the future')
        end
    end
end

99_cats/nine9_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

99_cats/nine9_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all.order(:id)
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :sex, :name, :description)
  end
end

99_cats/nine9_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

99_cats/nine9_cats/app/views/cats/index.html.erb
<h1>
  All cats:
</h1>

<ol>
  <% @cats.each do |cat| %>
    <li>
      <a href="<%= cat_url(cat.id) %>">
        <%= cat.name %>
      </a>
    </li>
  <% end %>
</ol>

99_cats/nine9_cats/app/views/cats/new.html.erb
<h1>Create new cat:</h1>
<form action="<%= cats_url %>" method="post">
    <label>Name:
        <input type="text" name="cat[name]">
    </label>

    <br>

    <label>Sex:</label>

    <label>Male:
        <input type="radio" name="cat[sex]" value="M">
    </label>
    <label>Female:
        <input type="radio" name="cat[sex]" value="F">
    </label>

    <br>

    <label>Select color:
        <select name="cat[color]">
        <option disabled selected>--Select Color--</option>
            <% Cat::CAT_COLORS.each do |color| %>
                <option value="<%= color %>"><%= color %></option>
            <% end %>
        </select>
    </label>

</form>

99_cats/nine9_cats/app/views/cats/show.html.erb
<h1>
  Cat details
</h1>

<table>
  <thead>
      <tr>
          <th colspan="2">About cat</th>
      </tr>
  </thead>
  <tbody>
        <tr>
            <td>Name</td>
            <td>Age</td>
            <td>Color</td>
            <td>Description</td>
        </tr>
        <tr>
            <td><%= @cat.name %></td>
            <td><%= @cat.age %></td>
            <td><%= @cat.color %></td>
            <td><%= @cat.description %></td>
        </tr>
  </tbody>
</table>

<a href="<%= cats_url %>">
  Back to all cats
</a>

99_cats/nine9_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nine9Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>